### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by miladvahdat** [mvahdatkhah/github-crash-course#1]
It looks better if the main title is more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #efa82e;
}
```
